baseURL = "/"
languageCode = "en-za"
title = "Feminism and Freedom"

themesDir = "themes"
theme = "hugo-whisper-theme"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Activities"
    url = "/activities/"
    weight = 2

[[menu.main]]
    name = "Readings"
    url = "/readings/"
    weight = 3

[params]
  # Which sections to render as main sections in themes.
  #
  # Hugo defaults to detecting a single main section:
  # tell it to include all our main sections.
  #
  # https://gohugo.io/functions/where/#mainsections
  # https://github.com/gohugoio/hugo/issues/3206
  # https://github.com/rdwatters/hugo-docs-concept/issues/79
  #
  mainSections = ["activities", "readings"]

  homepage_button_link = '/activities/'
  homepage_button_text = 'Start'

  [params.logo]
      mobile = "/images/logo-mobile.svg"
      standard  = "/images/logo.svg"
